src/accounts/urls.py
from django.urls.conf import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.AccountLoginView.as_view(), name='login'),
    path('logout', views.AccountLogoutViev.as_view(), name='logout'),
    path('register', views.AccountCreateView.as_view(), name='register'),
    path('profile', views.AccountUpdateView.as_view(), name='profile'),
    path('password/', views.AccountPasswordView.as_view(), name='password'),
    path('contact_us/', views.ContactUsView.as_view(), name='contact_us')
]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

API_PREFIX = 'api/v1'

urlpatterns = [
    # UI
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('testify.urls')),

    # API
    path(f'{API_PREFIX}/testify/', include('testify.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/testify/urls.py
from django.urls.conf import path

from . import views

app_name = 'testify'

urlpatterns = [
    path('', views.index, name='index'),
    path('leaderboard', views.leaderboard, name='leaderboard'),
    path('test/<str:uuid>', views.TestDetailView.as_view(), name='test'),
    path('<str:uuid>/start', views.TestRunnerView.as_view(), name='start'),
    path('<str:uuid>/next/', views.QuestionView.as_view(), name='question'),
    path('<str:uuid>/restart', views.restart_test, name='restart'),
]

handler404 = views.error_404
handler500 = views.error_500
handler400 = views.error_400
handler403 = views.error_403

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <body>
        <div>       
            <ul class="nav justify-content-center">
                <li class="nav-item">
                <a class="nav-link active" href="{% url 'testify:index' %}">Index</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'testify:leaderboard' %}">Leaderboard</a>
                </li>
                
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link p-1 m-1" href="{% url 'accounts:profile' %}">Logged in as <b>{{ user.username }}</b>  <img class="rounded-circle" width="25px" height="25px" src="{{ user.image.url }}"></a>
                    
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:contact_us' %}">Contact Us</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                  </li>
                {% endif%}
            </ul>
          </div>
          <hr>
        {% include 'includes/messages_handler.html' %}
        {% block body %}
        {% endblock %}
    </body>
</html>