src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

API_PREFIX = 'api/v1'

urlpatterns = [
    # UI
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('testify.urls')),

    # API
    path(f'{API_PREFIX}/testify/', include('testify.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/testify/api/urls.py
from django.urls import path
from testify.api.views import TestListCreateView, TestUpdateDeleteView

app_name = 'api_testify'

urlpatterns = [
    path('tests', TestListCreateView.as_view(), name='tests'),
    path('tests/<int:pk>', TestUpdateDeleteView.as_view(), name='tests_update')
]

src/testify/urls.py
from django.urls.conf import path

from . import views

app_name = 'testify'

urlpatterns = [
    path('', views.index, name='index'),
    path('leaderboard', views.leaderboard, name='leaderboard'),
    path('test/<str:uuid>', views.TestDetailView.as_view(), name='test'),
    path('<str:uuid>/start', views.TestRunnerView.as_view(), name='start'),
    path('<str:uuid>/next/', views.QuestionView.as_view(), name='question'),
    path('<str:uuid>/restart', views.restart_test, name='restart'),
]

handler404 = views.error_404
handler500 = views.error_500
handler400 = views.error_400
handler403 = views.error_403

src/testify/models.py
import datetime as dt

from django.db import models
from django.shortcuts import get_object_or_404

from accounts.models import User
from core.utils import generate_uuid
# Create your models here.


class Test(models.Model):
    class DIFFICULTY(models.IntegerChoices):
        VERY_EASY = 1, 'Very easy',
        EASY = 2, 'Easy',
        MEDIUM = 3, 'Medium',
        HARD = 4, 'HARD',
        VERY_HARD = 5, 'Very hard'
    uuid = models.UUIDField(default=generate_uuid)
    name = models.CharField(max_length=64)
    company_name = models.CharField(max_length=64)
    creation_date = models.DateTimeField(auto_now_add=True)
    description = models.TextField(max_length=512)
    difficulty = models.PositiveIntegerField(default=DIFFICULTY.VERY_EASY)
    best_result = models.ForeignKey(to=User, on_delete=models.SET_NULL, primary_key=False, null=True)
    last_run = models.DateTimeField(null=True)

    @property
    def questions_count(self):
        return self.questions.count()

    def reward(self):
        return self.questions_count * self.difficulty

    def __str__(self):
        return f'{self.name} - {self.questions_count}'


class Question(models.Model):
    test = models.ForeignKey(to=Test, related_name='questions', on_delete=models.CASCADE)
    question = models.TextField(max_length=1280)
    index = models.IntegerField(default=1)

    def __str__(self):
        return self.question


class Answer(models.Model):
    question = models.ForeignKey(to=Question, related_name='answers', on_delete=models.CASCADE)
    text = models.CharField(max_length=1280)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class TestParticipant(models.Model):
    class STATE(models.IntegerChoices):
        NEW = 0, 'New',
        COMPLETE = 1, "Completed"
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    test = models.ForeignKey(to=Test, on_delete=models.CASCADE, related_name='participation')
    state = models.PositiveIntegerField(default=STATE.NEW, choices=STATE.choices)
    date_started = models.DateTimeField(auto_now_add=True)
    write_date = models.DateTimeField(auto_now=True)
    num_correct_ans = models.PositiveIntegerField(default=0)
    num_incorrect_ans = models.PositiveIntegerField(default=0)
    is_passed = models.BooleanField(default=False)
    date_complete = models.DateTimeField(null=True, blank=True)
    current_question = models.IntegerField(default=1)

    def compute_finals(self):
        self.state = TestParticipant.STATE.COMPLETE
        self.date_complete = self.write_date
        self.time_spent = self.date_complete - self.date_started
        if self.points() > 0:
            self.is_passed = True
        self.save()

    def points(self):
        return max(0, self.num_correct_ans - self.num_incorrect_ans)

    def time_spent(self):
        time = self.write_date - self.date_started
        return time - dt.timedelta(microseconds=time.microseconds)

    @classmethod
    def get_self_object_new(cls, request, uuid):
        return get_object_or_404(
            klass=cls,
            user=request.user,
            state=cls.STATE.NEW,
            test__uuid=uuid,
        )

    @classmethod
    def get_self_object_complete(cls, request, uuid):
        return get_object_or_404(
            klass=cls,
            user=request.user,
            state=cls.STATE.COMPLETE,
            test__uuid=uuid,
        )

    def __str__(self):
        return f'{self.test.name} - {self.user.username}'

src/testify/forms.py
from django.core.exceptions import ValidationError
from django.forms import fields
from django.forms.models import BaseInlineFormSet, modelformset_factory
from django import forms

from testify.models import Answer, Question


class AnswerInlineFormSet(BaseInlineFormSet):
    def clean(self):
        num_correct_answers = sum([
            1
            for form in self.forms
            if form.cleaned_data['is_correct']
        ])

        if num_correct_answers == 0:
            raise ValidationError('At LEAST one answer must be correct!')

        if num_correct_answers == len(self.forms):
            raise ValidationError('ALL answers must not be CORRECT')


class QuestionInlineFormSet(BaseInlineFormSet):
    def clean(self):
        indexes = []
        for form in self.forms:
            ind = form.cleaned_data['index']
            if ind in indexes:
                raise ValidationError('INDEX must be UNIQUE')
            indexes.append(ind)
        indexes.sort()
        for item in indexes:
            if item == indexes[0]:
                continue
            elif (item - 1) not in indexes:
                raise ValidationError('Indexes of the QUESTIONS must be in order!')
        if indexes[0] != 1:
            raise ValidationError('Index of the FIRST QUESTION must be 1!')


class AnswerForm(forms.ModelForm):
    is_selected = forms.BooleanField(required=False)
    test = fields.CharField()

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['text'].label = ''
        self.fields['is_selected'].label = ''

    class Meta:
        model = Answer
        fields = ['text', 'is_selected']
        widgets = {
            'question': forms.TextInput(attrs={'readonly': True})
        }


class QuestionAdminForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'


class AnswerAdminForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = '__all__'


AnswerFormSet = modelformset_factory(
    model=Answer,
    form=AnswerForm,
    extra=0,
)

src/testify/api/views.py
from rest_framework import generics

from testify.api.serializers import TestSerializer
from testify.models import Test


class TestListCreateView(generics.ListCreateAPIView):
    queryset = Test.objects.all()
    serializer_class = TestSerializer


class TestUpdateDeleteView(generics.RetrieveUpdateAPIView):
    queryset = Test.objects.all()
    serializer_class = TestSerializer


class TestDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Test.objects.all()
    serializer_class = TestSerializer

src/testify/views.py
from django.shortcuts import redirect, render
from django.urls.base import reverse
from django.views import View
from django.contrib import messages

from .forms import AnswerFormSet
from .models import Question, Test, TestParticipant
from accounts.models import User
from core.models import TestBaseDetailView, TestLogic
from core.views import LoginRequiredBaseMixin

# Create your views here.


def index(request):
    return render(request, 'testify/index.html', {
        'tests': Test.objects.all(),
    })


def leaderboard(request):
    return render(request, 'testify/leaderboard.html', {
        'persons': User.objects.order_by('-rating'),
    })


class TestDetailView(TestBaseDetailView):
    model = Test
    template_name = 'testify/test.html'
    context_object_name = 'test'
    pk_url_kwarg = 'uuid'


def restart_test(request, uuid):
    TestParticipant.get_self_object_new(request, uuid).delete()
    return redirect(reverse('testify:start', args=[uuid]))


class TestRunnerView(LoginRequiredBaseMixin, View):
    def get(self, request, uuid):
        user = request.user
        state = TestParticipant.STATE.NEW
        test = Test.objects.get(uuid=uuid)
        if TestParticipant.objects.filter(user=user, state=state, test=test).count() == 0:
            TestParticipant.objects.create(
                user=user,
                state=state,
                test=test
            )
        return redirect(reverse('testify:question', args=[uuid, ]))


class QuestionView(View):
    def get(self, request, uuid):
        test_result = TestParticipant.get_self_object_new(request, uuid)
        question = Question.objects.get(test__uuid=uuid, index=test_result.current_question)
        answers = question.answers.all()
        form_set = AnswerFormSet(queryset=answers)
        return render(request, 'testify/passing.html', {
            'question': question,
            'form_set': form_set,
        })

    def post(self, request, uuid):
        forms_list = AnswerFormSet(data=request.POST).forms
        test_logic = TestLogic(TestParticipant.get_self_object_new(request, uuid))
        test_result = test_logic.get_test_result(forms_list)
        if request.user.show_result_popup:
            if test_logic.point:
                messages.success(self.request, "Well Done! That's correct!")
            else:
                messages.error(self.request, "Oops! That's wrong!")
        if test_logic.is_last():
            test_logic.actions_for_completion()
            test = test_result.test
            return render(request, 'testify/completetest.html', {
                'test_result': test_result,
                'test': test
            })

        return redirect(reverse('testify:question', args=[uuid, ]))


def error_400(request, exception):
    data = {}
    return render(request, 'testify/error_handlers/error_400.html', data)


def error_403(request, exception):
    data = {}
    return render(request, 'testify/error_handlers/error_403.html', data)


def error_404(request, exception):
    data = {}
    return render(request, 'testify/error_handlers/error_404.html', data)


def error_500(request):
    data = {}
    return render(request, 'testify/error_handlers/error_500.html', data)

src/testify/templates/testify/completetest.html
{% extends 'base.html' %}
{% load math_func %}
{% block body %}
<div class="jumbotron">
    <h1 class="display-4">Congratulations!</h1>
    <p class="lead">You've complete the test! - <b>{{ test.name }}</b></p>
    <p>You scored {{ test_result.num_correct_ans }} out of {{ test.questions_count }}
    {% expr '%1/%2*100' test_result.num_correct_ans test_result.test.questions_count as progress %}
    {% if test_result.is_passed %}
        <div class="progress">
            <div class="progress-bar bg-success" role="progressbar" style="width: {{ progress }}%" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100">{{ progress }}%</div>
        </div></p>
        <p>You successfully passed the test!</p>
    {% else %}
        <div class="progress">
            <div class="progress-bar bg-danger" role="progressbar" style="width: {{ progress }}%" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100">{{ progress }}%</div>
        </div></p>
        <p>Unfortunately you scored below required! Try Again later!</p>
    {% endif %}
    <p>Completion date/time: {{ test_result.date_complete }}</p>
    <p>Time spent: {{ test_result.time_spent}}</p>
    <hr class="my-4">
    <p>Good job! Try another tests on our website!</p>
    <a class="btn btn-primary btn-lg" href="{% url 'testify:index' %}" role="button">Home Page</a>
  </div>

{% endblock %}

src/testify/templates/testify/continue.html
{% extends 'base.html' %}

{% block body %}

Attention! You have uncompleted test with this name. Do you wish to continue?

<div>
    <a class="btn btn-success" href="{% url 'testify:restart' uuid %}">Restart test</a>
    <a class="btn btn-success" href="{% url 'testify:continue' uuid=uuid index=index %}">Continue</a>
</div>
{% endblock %}

src/testify/templates/testify/index.html
{% extends 'base.html' %}
{% load img_indication %}
{% block title %}Testify Main{% endblock %}
{% block body %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Company name</th>
        <th scope="col">Nr. of Questions</th>
        <th scope="col">Difficulty</th>
        <th scope="col">Participate</th>
      </tr>
    </thead>
    {% for test in tests %}
    <tbody>
        <tr>
            <td><a href="{% url 'testify:test' test.uuid %}">{{ test.name }}</a></td>
            <td>{{ test.company_name }}</td>
            <td>{{ test.questions_count }}</td>
            
            <td><img width="75px" height="45px" src="{% difficulty test.difficulty %}" </td>
            <td><a href="{% url 'testify:start' test.uuid %}">Pass the test</a></td>
        </tr>
    </tbody>
    {% endfor %}
</table>
{% endblock %}

src/testify/templates/testify/leaderboard.html
{% extends 'base.html' %}

{% block title %}Leaderboard{% endblock %}
{% block body %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"></th>
        <th scope="col">Username</th>
        <th scope="col">Rating</th>
      </tr>
    </thead>
    {% for person in persons %}
    <tbody>
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><img class="rounded-circle" width="25px" height="25px" src="{{ person.image.url }}"></td>
            <td>{{ person.username }}</td>
            <td>{{ forloop.counter }} of {{ persons.count }}</td>
        </tr>
    </tbody>
    {% endfor %}
</table>
{% endblock %}

src/testify/templates/testify/passing.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load math_func %}

{% block title %}{% endblock %}
{% block body %}
  {% expr '(%1-1)/%2*100' question.index question.test.questions_count as progress %}
  <div class="progress">
    <div class="progress-bar" role="progressbar" style="width: {{ progress }}%" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
  <form method="POST">
    {% csrf_token %}
    {{ form_set.management_form }}
    Question # {{ question.index }}/{{ question.test.questions_count }}: <b>{{ question.question }}</b>
    {% for form in form_set %}
      {{ form|crispy }}

    {% endfor %}
    <button type="submit" class="btn btn-success">Submit</button>
  </form>
{% endblock %}

src/testify/templates/testify/test.html
{% extends 'base.html' %}

{% block title %}Test Info{% endblock %}
{% block body %}
    
    <div class="card m-3" style="width: 80%; background-color:azure;">
        <div class="card-body">
          <h5 class="card-title">Test: {{ test.name }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">By: {{test.company_name}}</p>
          <p>Number of questions: {{ test.questions_count }}</p>
          <p>Best result by: {{ test.best_result.username }}</p>
          <p>Last run: {{ test.last_run }}</p>
          {% if current_started %}
          <p>Current unfinished run: {{ current_started.date_started }}</p>
          {% endif %}
          {% if continue %}
            <div>
              <a class="btn btn-danger" href="{% url 'testify:restart' test.uuid %}">Restart test</a>
              <a class="btn btn-warning" href="{% url 'testify:start' test.uuid %}">Continue</a>
            </div>
          {% else %} 
            <a class="btn btn-success" href="{% url 'testify:start' test.uuid %}">Start</a>
          {% endif %}
        </div>
      </div>
      <table class="table p-3 m-4" style="background-color: rgb(203, 255, 196); width:75%">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">User</th>
            <th scope="col">Time spent</th>
            <th scope="col">Points</th>
          </tr>
        </thead>
        {% for result in results %}
        <tbody>
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ result.user.username }}</td>
                <td>{{ result.time_spent }}</td>
                <td>{{ result.points }}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
{% endblock %}