src/accounts/urls.py
from django.urls.conf import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.AccountLoginView.as_view(), name='login'),
    path('logout', views.AccountLogoutViev.as_view(), name='logout'),
    path('register', views.AccountCreateView.as_view(), name='register'),
    path('profile', views.AccountUpdateView.as_view(), name='profile'),
    path('password/', views.AccountPasswordView.as_view(), name='password'),
    path('contact_us/', views.ContactUsView.as_view(), name='contact_us')
]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

API_PREFIX = 'api/v1'

urlpatterns = [
    # UI
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('testify.urls')),

    # API
    path(f'{API_PREFIX}/testify/', include('testify.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/testify/urls.py
from django.urls.conf import path

from . import views

app_name = 'testify'

urlpatterns = [
    path('', views.index, name='index'),
    path('leaderboard', views.leaderboard, name='leaderboard'),
    path('test/<str:uuid>', views.TestDetailView.as_view(), name='test'),
    path('<str:uuid>/start', views.TestRunnerView.as_view(), name='start'),
    path('<str:uuid>/next/', views.QuestionView.as_view(), name='question'),
    path('<str:uuid>/restart', views.restart_test, name='restart'),
]

handler404 = views.error_404
handler500 = views.error_500
handler400 = views.error_400
handler403 = views.error_403

src/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from core.utils import generate_uuid
# Create your models here.


class User(AbstractUser):
    uuid = models.UUIDField(default=generate_uuid)
    bio = models.TextField(max_length=512, blank=True)
    location = models.CharField(max_length=64, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_img = models.ImageField(null=True, default='default.jpeg', upload_to='profile_imgs')
    rating = models.PositiveIntegerField(default=0)
    show_result_popup = models.BooleanField(default=False)

    def add_points_to_rating(self, test_reward):
        self.rating += test_reward
        self.save(update_fields=['rating'])

    def __str__(self):
        return self.username

src/accounts/forms.py
from django import forms
from django.forms import ModelForm, Form, fields
from accounts.models import User
from django.contrib.auth.forms import PasswordChangeForm


class AccountCreateForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'bio',
            'location',
            'birth_date',
            'show_result_popup',
            'profile_img',
        ]


class AccountUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'bio',
            'location',
            'birth_date',
            'show_result_popup',
            'profile_img',
        ]


class AccountPasswordForm(PasswordChangeForm):
    pass


class ContactUs(Form):
    subject = fields.CharField(max_length=256, empty_value='Message from Testify')
    message = fields.CharField(widget=forms.Textarea)

src/accounts/views.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, FormView, UpdateView
from django.core.mail import send_mail
from django.conf import settings

from accounts.forms import AccountCreateForm, AccountPasswordForm, AccountUpdateForm, ContactUs

from .models import User
# Create your views here.


class AccountLoginView(LoginView):
    template_name = 'accounts/login.html'

    def get_redirect_url(self):
        return reverse('testify:index')


class AccountLogoutViev(LogoutView):
    template_name = 'accounts/logout.html'


class AccountPasswordView(PasswordChangeView):
    template_name = 'accounts/password.html'
    form_class = AccountPasswordForm
    success_url = reverse_lazy('accounts:profile')


class AccountCreateView(CreateView):
    model = User
    template_name = 'accounts/register.html'
    form_class = AccountCreateForm
    success_url = reverse_lazy('testify:index')


class AccountUpdateView(UpdateView):
    template_name = 'accounts/profile.html'
    model = User
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accounts:profile')

    def get_object(self):
        return self.request.user


class ContactUsView(FormView):
    template_name = 'accounts/contact_us.html'
    extra_context = {'title': 'Send us a message!'}
    success_url = reverse_lazy('testify:index')
    form_class = ContactUs

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            send_mail(
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message'],
                from_email=request.user.email,
                recipient_list=settings.EMAIL_HOST_RECIPIENT.split(':'),
            )
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

src/accounts/templates/accounts/contact_us.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Contact Us
    {% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Send">
        </form>
    {% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Log in user
    {% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Log in">
        </form>
    {% endblock %}

src/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Log Out
    {% endblock %}
    {% block body %}
        <a class="btn btn-light" href="{% url 'accounts:login' %}">Log in</a>
        <a class="btn btn-light" href="{% url 'testify:index' %}">Home</a>
    {% endblock %}

src/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Password Change Page
    {% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Change Password">
        </form>
    {% endblock %}

src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Profile page
    {% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Save">
            <a class="btn btn-light" href="{% url 'accounts:password' %}">Change password</a>
        </form>
    {% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}
        Register New User
    {% endblock %}
    {% block body %}
        <form method="POST">
            {% csrf_token %}
        
            {{ form|crispy }}
            
            <input class="btn btn-light" type="submit" value="Register">
        </form>
    {% endblock %}